spring.application.name=QuickAI
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/learning
spring.datasource.username=postgres
spring.datasource.password=Shivam@2005
gemini.api.key=${GEMINI_API_KEY}
gemini.api.key2=${GEMINI_API_KEY2}
gemini.api.key3=${GEMINI_API_KEY3}
gemini.api.key4=${GEMINI_API_KEY4}
mistral.api.key=${MISTRAL_API_KEY}
groq.api.key=${GROQ_API_KEY}
hugging.api.key=${HUGGINGFACE_API_KEY}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
